version: '3.8'

services:
  bolgenerator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bolgenerator
    ports:
      - "3000:3000"
    volumes:
      - ./Tests:/app/Tests
    restart: always
